# Generated by Django 5.0.2 on 2024-08-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Customer Query', 'verbose_name_plural': 'Customer Queries'},
        ),
    ]
