# Generated by Django 5.0.2 on 2024-09-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(default='1'),
        ),
    ]
