# Generated by Django 5.0.2 on 2024-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(blank=True, default='1', null=True),
        ),
    ]
