# Generated by Django 5.0.2 on 2024-08-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Property list'},
        ),
        migrations.AlterModelOptions(
            name='poi',
            options={'verbose_name': 'Point of Interest', 'verbose_name_plural': 'Points of Interest'},
        ),
    ]
